"""add produto vendaitem preco_regional status_pedido

Revision ID: 97b67bcd926f
Revises: f3f6c1f01097
Create Date: 2026-04-01 10:34:07.751687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b67bcd926f'
down_revision: Union[str, Sequence[str], None] = 'f3f6c1f01097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('preco_tabela', sa.Float(), nullable=False),
    sa.Column('preco_minimo', sa.Float(), nullable=False),
    sa.Column('comissao_pct', sa.Float(), nullable=False),
    sa.Column('ipi_pct', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('ean', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_categoria'), 'produtos', ['categoria'], unique=False)
    op.create_index(op.f('ix_produtos_codigo'), 'produtos', ['codigo'], unique=True)
    op.create_table('precos_regionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'uf', name='uq_produto_uf')
    )
    op.create_index(op.f('ix_precos_regionais_produto_id'), 'precos_regionais', ['produto_id'], unique=False)
    op.create_table('venda_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('desconto_pct', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.CheckConstraint('valor_total > 0', name='ck_venda_item_valor_positivo'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_itens_produto_id'), 'venda_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_venda_itens_venda_id'), 'venda_itens', ['venda_id'], unique=False)
    op.create_index('ix_venda_itens_venda_produto', 'venda_itens', ['venda_id', 'produto_id'], unique=False)
    op.add_column('vendas', sa.Column('status_pedido', sa.String(length=20), nullable=False))
    op.add_column('vendas', sa.Column('condicao_pagamento', sa.String(length=100), nullable=True))
    op.add_column('vendas', sa.Column('observacao', sa.Text(), nullable=True))
    op.create_index(op.f('ix_vendas_status_pedido'), 'vendas', ['status_pedido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_status_pedido'), table_name='vendas')
    op.drop_column('vendas', 'observacao')
    op.drop_column('vendas', 'condicao_pagamento')
    op.drop_column('vendas', 'status_pedido')
    op.drop_index('ix_venda_itens_venda_produto', table_name='venda_itens')
    op.drop_index(op.f('ix_venda_itens_venda_id'), table_name='venda_itens')
    op.drop_index(op.f('ix_venda_itens_produto_id'), table_name='venda_itens')
    op.drop_table('venda_itens')
    op.drop_index(op.f('ix_precos_regionais_produto_id'), table_name='precos_regionais')
    op.drop_table('precos_regionais')
    op.drop_index(op.f('ix_produtos_codigo'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
