"""initial schema

Revision ID: f3f6c1f01097
Revises: 
Create Date: 2026-04-01 10:13:53.072887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f6c1f01097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('codigo_cliente', sa.String(length=20), nullable=True),
    sa.Column('tipo_cliente_sap', sa.String(length=50), nullable=True),
    sa.Column('macroregiao', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('rede_regional', sa.String(length=100), nullable=True),
    sa.Column('consultor', sa.String(length=50), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=30), nullable=True),
    sa.Column('classificacao_3tier', sa.String(length=15), nullable=True),
    sa.Column('dias_sem_compra', sa.Integer(), nullable=True),
    sa.Column('valor_ultimo_pedido', sa.Float(), nullable=True),
    sa.Column('ciclo_medio', sa.Float(), nullable=True),
    sa.Column('n_compras', sa.Integer(), nullable=True),
    sa.Column('faturamento_total', sa.Float(), nullable=True),
    sa.Column('tipo_contato', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('estagio_funil', sa.String(length=50), nullable=True),
    sa.Column('acao_futura', sa.String(length=100), nullable=True),
    sa.Column('fase', sa.String(length=30), nullable=True),
    sa.Column('temperatura', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('prioridade', sa.String(length=5), nullable=True),
    sa.Column('sinaleiro', sa.String(length=20), nullable=True),
    sa.Column('curva_abc', sa.String(length=1), nullable=True),
    sa.Column('followup_dias', sa.Integer(), nullable=True),
    sa.Column('grupo_dash', sa.String(length=50), nullable=True),
    sa.Column('tipo_acao', sa.String(length=50), nullable=True),
    sa.Column('tentativas', sa.String(length=5), nullable=True),
    sa.Column('problema_aberto', sa.Boolean(), nullable=True),
    sa.Column('followup_vencido', sa.Boolean(), nullable=True),
    sa.Column('cs_no_prazo', sa.Boolean(), nullable=True),
    sa.Column('meta_anual', sa.Float(), nullable=True),
    sa.Column('realizado_acumulado', sa.Float(), nullable=True),
    sa.Column('pct_alcancado', sa.Float(), nullable=True),
    sa.Column('gap_valor', sa.Float(), nullable=True),
    sa.Column('status_meta', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cnpj'), 'clientes', ['cnpj'], unique=True)
    op.create_index(op.f('ix_clientes_consultor'), 'clientes', ['consultor'], unique=False)
    op.create_index(op.f('ix_clientes_curva_abc'), 'clientes', ['curva_abc'], unique=False)
    op.create_index(op.f('ix_clientes_prioridade'), 'clientes', ['prioridade'], unique=False)
    op.create_index(op.f('ix_clientes_sinaleiro'), 'clientes', ['sinaleiro'], unique=False)
    op.create_index(op.f('ix_clientes_situacao'), 'clientes', ['situacao'], unique=False)
    op.create_index(op.f('ix_clientes_temperatura'), 'clientes', ['temperatura'], unique=False)
    op.create_table('redes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('total_lojas', sa.Integer(), nullable=False),
    sa.Column('lojas_ativas', sa.Integer(), nullable=False),
    sa.Column('consultor_responsavel', sa.String(length=50), nullable=True),
    sa.Column('faturamento_real', sa.Float(), nullable=True),
    sa.Column('potencial_maximo', sa.Float(), nullable=True),
    sa.Column('pct_penetracao', sa.Float(), nullable=True),
    sa.Column('sinaleiro', sa.String(length=20), nullable=True),
    sa.Column('cadencia', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('regras_motor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('estagio_funil', sa.String(length=50), nullable=False),
    sa.Column('fase', sa.String(length=30), nullable=False),
    sa.Column('tipo_contato', sa.String(length=50), nullable=False),
    sa.Column('acao_futura', sa.String(length=100), nullable=False),
    sa.Column('temperatura', sa.String(length=20), nullable=False),
    sa.Column('follow_up_dias', sa.Integer(), nullable=False),
    sa.Column('grupo_dash', sa.String(length=50), nullable=True),
    sa.Column('tipo_acao', sa.String(length=50), nullable=True),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave'),
    sa.UniqueConstraint('situacao', 'resultado', name='uq_regra_sit_res')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('consultor_nome', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('consultor', sa.String(length=50), nullable=False),
    sa.Column('data_agenda', sa.Date(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('temperatura', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('prioridade', sa.String(length=5), nullable=True),
    sa.Column('sinaleiro', sa.String(length=20), nullable=True),
    sa.Column('acao', sa.String(length=200), nullable=True),
    sa.Column('followup_dias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_cnpj'), 'agenda_items', ['cnpj'], unique=False)
    op.create_index(op.f('ix_agenda_items_consultor'), 'agenda_items', ['consultor'], unique=False)
    op.create_index(op.f('ix_agenda_items_data_agenda'), 'agenda_items', ['data_agenda'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('campo', sa.String(length=50), nullable=False),
    sa.Column('valor_anterior', sa.String(length=255), nullable=True),
    sa.Column('valor_novo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_cnpj'), 'audit_logs', ['cnpj'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registros_lidos', sa.Integer(), nullable=True),
    sa.Column('registros_inseridos', sa.Integer(), nullable=True),
    sa.Column('registros_atualizados', sa.Integer(), nullable=True),
    sa.Column('registros_ignorados', sa.Integer(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_interacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('data_interacao', sa.DateTime(), nullable=False),
    sa.Column('consultor', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estagio_funil', sa.String(length=50), nullable=True),
    sa.Column('fase', sa.String(length=30), nullable=True),
    sa.Column('tipo_contato', sa.String(length=50), nullable=True),
    sa.Column('acao_futura', sa.String(length=100), nullable=True),
    sa.Column('temperatura', sa.String(length=20), nullable=True),
    sa.Column('follow_up_dias', sa.Integer(), nullable=True),
    sa.Column('grupo_dash', sa.String(length=50), nullable=True),
    sa.Column('tentativa', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_cnpj_data', 'log_interacoes', ['cnpj', 'data_interacao'], unique=False)
    op.create_index('ix_log_consultor_data', 'log_interacoes', ['consultor', 'data_interacao'], unique=False)
    op.create_index(op.f('ix_log_interacoes_cnpj'), 'log_interacoes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_log_interacoes_consultor'), 'log_interacoes', ['consultor'], unique=False)
    op.create_index(op.f('ix_log_interacoes_data_interacao'), 'log_interacoes', ['data_interacao'], unique=False)
    op.create_table('metas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('meta_sap', sa.Float(), nullable=False),
    sa.Column('meta_igualitaria', sa.Float(), nullable=True),
    sa.Column('realizado', sa.Float(), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj', 'ano', 'mes', name='uq_meta_cnpj_periodo')
    )
    op.create_index('ix_meta_periodo', 'metas', ['ano', 'mes'], unique=False)
    op.create_index(op.f('ix_metas_cnpj'), 'metas', ['cnpj'], unique=False)
    op.create_table('rnc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('consultor', sa.String(length=50), nullable=False),
    sa.Column('tipo_problema', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prazo_resolucao', sa.Date(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('resolucao', sa.Text(), nullable=True),
    sa.Column('data_resolucao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rnc_cnpj'), 'rnc', ['cnpj'], unique=False)
    op.create_index(op.f('ix_rnc_consultor'), 'rnc', ['consultor'], unique=False)
    op.create_table('score_historico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('data_calculo', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('prioridade', sa.String(length=5), nullable=True),
    sa.Column('sinaleiro', sa.String(length=20), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('fator_urgencia', sa.Float(), nullable=True),
    sa.Column('fator_valor', sa.Float(), nullable=True),
    sa.Column('fator_followup', sa.Float(), nullable=True),
    sa.Column('fator_sinal', sa.Float(), nullable=True),
    sa.Column('fator_tentativa', sa.Float(), nullable=True),
    sa.Column('fator_situacao', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_hist_cnpj_data', 'score_historico', ['cnpj', 'data_calculo'], unique=False)
    op.create_index(op.f('ix_score_historico_cnpj'), 'score_historico', ['cnpj'], unique=False)
    op.create_index(op.f('ix_score_historico_data_calculo'), 'score_historico', ['data_calculo'], unique=False)
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=True),
    sa.Column('valor_pedido', sa.Float(), nullable=False),
    sa.Column('consultor', sa.String(length=50), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('classificacao_3tier', sa.String(length=15), nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('valor_pedido > 0', name='ck_venda_valor_positivo'),
    sa.ForeignKeyConstraint(['cnpj'], ['clientes.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_cnpj'), 'vendas', ['cnpj'], unique=False)
    op.create_index('ix_vendas_cnpj_data', 'vendas', ['cnpj', 'data_pedido'], unique=False)
    op.create_index(op.f('ix_vendas_consultor'), 'vendas', ['consultor'], unique=False)
    op.create_index(op.f('ix_vendas_data_pedido'), 'vendas', ['data_pedido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_data_pedido'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_consultor'), table_name='vendas')
    op.drop_index('ix_vendas_cnpj_data', table_name='vendas')
    op.drop_index(op.f('ix_vendas_cnpj'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_score_historico_data_calculo'), table_name='score_historico')
    op.drop_index(op.f('ix_score_historico_cnpj'), table_name='score_historico')
    op.drop_index('ix_score_hist_cnpj_data', table_name='score_historico')
    op.drop_table('score_historico')
    op.drop_index(op.f('ix_rnc_consultor'), table_name='rnc')
    op.drop_index(op.f('ix_rnc_cnpj'), table_name='rnc')
    op.drop_table('rnc')
    op.drop_index(op.f('ix_metas_cnpj'), table_name='metas')
    op.drop_index('ix_meta_periodo', table_name='metas')
    op.drop_table('metas')
    op.drop_index(op.f('ix_log_interacoes_data_interacao'), table_name='log_interacoes')
    op.drop_index(op.f('ix_log_interacoes_consultor'), table_name='log_interacoes')
    op.drop_index(op.f('ix_log_interacoes_cnpj'), table_name='log_interacoes')
    op.drop_index('ix_log_consultor_data', table_name='log_interacoes')
    op.drop_index('ix_log_cnpj_data', table_name='log_interacoes')
    op.drop_table('log_interacoes')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_cnpj'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agenda_items_data_agenda'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_consultor'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_cnpj'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('regras_motor')
    op.drop_table('redes')
    op.drop_index(op.f('ix_clientes_temperatura'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_situacao'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_sinaleiro'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_prioridade'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_curva_abc'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_consultor'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
